### ISSUE TITLE
“笨方法”练WOOP

### ISSUE THREAD

**Issue by MaiYunfei2000** [MaiYunfei2000/i-love-study#14]
# 🚧🚜

> 没工夫仔细琢磨WOOP？不熟悉WOOP的流程规范？没关系，你可以马上零门槛入门！

    大标题备选：
    ①“笨方法”练WOOP
    ②极简四步走，执行神器WOOP快速入门

WOOP，大名为「**心理对比与执行意图**(Mental Contrasting with Implementation Intention, MCII)」，是一把有效提升执行效率的大杀器。心理学大牛格尔维茨 (Peter Gollwitzer)和厄廷根 (Gabriele Oettingen)  这对夫妻分别贡献了「心理对比」和「执行意图」。这两把利器能够从底层HACK人类心智，然而它们还可以双剑合璧，继续大大提升威力！

心里先想象美好愿望，后想象现实障碍，这种对峙过程称「心理对比」，可以代表**WOOP的前三个字母**。“如果X，那么Y”，这种区别于目标意图“设立目标-完成目标”的行动方式被称为「执行意图」，可以代表**WOOP的后两个字母**。此不详述，看一下阳老师的[《行动派》](https://mp.weixin.qq.com/s/h2di9jlO8T1BAoxwqq-7ow)以及厄廷根老师的《WOOP思维心理学》吧。

这两周（5月6日-19日）的安人书院共读书目就是这本书。也许很多小伙伴翻了书后都和我一样都隐隐有个困惑：在书中看了很多案例，WOOP的使用步骤也很好记，可是……可是……我还是觉得没法好好地用起它来！

万事开头难，谁让大脑喜欢偷懒。想象事情占用认知资源，调用WOOP的具体操作过程及注意事项也占用认知资源，而处于信息过载时代的我们已经被各种事物折腾得头脑发涨。我不干我不干，我要有人手把手地帮我做WOOP！这不，当我翻到最后一章时，欣喜地发现厄廷根老师很贴心地给我们准备了一个帮助我们做WOOP的免费APP。既然已经有了造好的轮子，尚为新手的我们为什么不用呢？

## 上篇 从零开始练WOOP

这款应用名字就叫“woop”，可在 APP Store (iOS) 和 Google Play Store (安卓，需要梯子) 免费下载安装。
￼
![home-woop](https://upload-images.jianshu.io/upload_images/15376232-a970ff4c299454e8.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

这是一款设计简洁的小应用，大大的加号按钮让我不假思索地点了下去。

#### 准备活动

![relax](https://upload-images.jianshu.io/upload_images/15376232-4d5314c4fc9b9389.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

请确保自己不会被打扰，然后把所有干扰注意力的事物放在一旁，清掉手机的后台并关闭网络。花几分钟好好地放松一下自己，在平静、舒适的时候开始WOOP~

接下来一起学习或复习一下整个流程吧！

#### 愿望 (Wish)

![iFmwT15dT%qCIzi2+qF0uQ_thumb_445.jpg](https://upload-images.jianshu.io/upload_images/15376232-1408b52c523fc2a1.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
###### 此处指导语的具体内容由前面选择的事情类别（职业生活/健康生活/人际关系）决定。

我的第一次WOOP用给哪件事呢？

对于生活复杂度不低的我们，提前规划好一天的事务是很重要的。可是传统的单纯依靠设定时间的事务规划方式并不总是靠谱，关于这一点，相信不少小伙伴都有些体会。那我不妨结合WOOP来规划今天的事务：想一下今天都有哪些要做的事，然后为每件事设定好WOOP脚本。

厄廷根老师说，WOOP大法好，我们要起床后WOOP一下，睡前WOOP一下，坐车时WOOP一下，排队时WOOP一下……好，都说“一日之计在于晨”，那我就先为起床后的WOOP来做一次WOOP吧！

我输入了我的愿望：早上起床时对今天规划的事情做一次全面的WOOP。

#### 结果 (Outcome)

![outcome](https://upload-images.jianshu.io/upload_images/15376232-03d92ecff0d789f0.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

最好的结果当然是，今天规划的各种事情都顺利完成了，我满足、愉悦地躺上床睡觉啦！

![imagine](https://upload-images.jianshu.io/upload_images/15376232-2ba2368773d81c70.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

花时间充分地想象一下这个结果！（如果着急地快速点按钮，会弹出温馨提示让你花多点时间好好想哦）

#### 障碍 (Obstacle)

![Obstacle](https://upload-images.jianshu.io/upload_images/15376232-b993fddb32cd8460.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

早晨嘛，在床上赖太久就什么都凉了。因此最大的障碍自然是未能及时起床，以及起床之后随便刷手机。

☁️然后再花时间充分地想象一下愿望受阻时的情景。情景A：我蜷缩在被窝中，听见闹钟响起后迅速将其掐灭。情景B：我终于坐了起来，睡眼惺忪地打开了手机，然后顺手点开知识星球，看看昨晚都有哪些小伙伴写了读书卡片？然后又顺手打开微信，然后又……

#### 计划 (Plan)

![Plan](https://upload-images.jianshu.io/upload_images/15376232-11725a290455f61e.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

一个行动怎么够？按照我前面的想法，得有两个！于是我输入：

	if 闹钟响起 then 立即弹起来做WOOP;
	if 想打开微信或知识星球等非效率APP then 打开Notes或WOOP立即WOOP一下！

接下来APP展示我的if-then计划并重复提醒我：确认一下你的计划吧，在心里慢慢地重复一下你的计划吧~

但我已经眉头皱起。这很不对……仔细看看这张卡片，看我得到个什么！

![final](https://upload-images.jianshu.io/upload_images/15376232-b3ca595f992e14e0.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

我才发觉我的WOOP技能还处于菜鸟级别，需要多加练习、练习、练习。

### 问题在哪里？

从一开始就出现了问题：我的愿望实际上是两件事——按时早起，以及做WOOP！

好的，那就拆分事件。

	Wish: 按时早起
	Outcome: 我可以有充裕时间练习WOOP
	Obstacle: 赖床
	Plan: if 闹钟响起 then 迅速弹起来

从这里可以看出，我们做WOOP时，应当**把目标及行动拆解成不可分割的最小单位**。

然而这张WOOP卡片还是存在问题，细心的同学应该已经从上一张截图里看出来了。Obstacle和Plan这两处地方还有问题：Obstacle应当是if，Plan应当是then——两者组合成一个执行意图。只有这样做时，APP上生成的卡片才看得通顺。

因此卡片这样写更好：

	Wish: 按时早起
	Outcome: 我可以有充裕时间练习WOOP
	Obstacle: 闹钟响起时犯困
	Plan: 迅速弹起来

然后另外一张卡片写成这样：

	Wish: 对今天的事情做WOOP
	Outcome: 今天规划的各种事情都顺利完成了，我满足、愉悦地躺上床睡觉
	Obstacle: 试图点开非效率工具
	Plan: 点开效率工具，开始WOOP

为什么一定要这样制作WOOP卡片，难道不是这个软件太死板了吗？非也~这恰是WOOP的精髓所在！

我做了这么一个猜想。大脑喜欢找不同；思考勾勒出记忆的痕迹（另一种说法则是「必要难度」）——两条认知规律在这里意味着什么？「心理对比」先美好幻想后现实障碍的做法，能使人们更深刻地认识到障碍的存在（相关的记忆存储得更加牢固）。此时，这个障碍的相关记忆更容易提取。而「执行意图」的发动条件(if)与实现愿望的障碍(Obstacle)挂钩时，脑中的if-then脚本就更容易运行。

也许猜想不一定对，但厄廷根老师的实证研究已表明使用「WOOP」比单纯使用「心理对比」或「执行意图」更能帮助人们行动。

两位武侠站在一条船上，两大宝具才能真正双剑合璧。否则，Mental Contrasting ***with*** Implementation Intention 就变成了 Mental Contrasting ***and*** Implementation Intention，无法产生 1 + 1 > 2 的组合技效果。（后一个英文短语是我在开玩笑哈，不要当真:D）

不到位的WOOP，除了前文的错误示范还有另一种常见例子：只使用「执行意图」。单纯套用if-then格式的做法并不万能，一个极端的例子就是设上一堆带备忘的闹钟或带提醒的备忘，听到某闹钟然后做某事。这真的很管用吗？这在执行意图进入我们视野之前就已经比较常见了，显然不一定管用。WOOP奏效的关键是把触发行动的条件内化，促使我们形成条件反射。我们不是机器人，不能像他们把代码写入运行内存一样轻松地将信息提取至工作记忆中。

因此我们在熟练掌握这个技能之前，先跟着APP的思路来练习吧。APP的反馈比自我反省更容易让我们发现自己不到位的地方。

现在可以得出APP的两个好处：

1. 不需要我们预先学习知识，从而降低认知负荷。
2. 帮助我们规范WOOP卡片的制作——从流程到具体内容都能规范。

我们仅需照着指示操作，就能一遍又一遍地重复使用WOOP框架。而框架的优点在于易复用，这就让WOOP成为了批量生成习惯的当前最优解。

## 下篇 WOOP进阶练习

所谓“师傅领进门，修行在个人”。厄廷根老师只能指引我们走进WOOP的世界，但不可能让我们一秒变成执行达人。将这个技能内化需要我们大时间周期的践行，一个量级一个量级地积累具体情境中的内隐知识。同时，现实生活中的事情多而复杂，也许需要做很多次WOOP才能克服重重障碍达成一个愿望。

比如，上个篇章中的WOOP实际上还没做完。早起的障碍除了犯困，还有晚睡。而造成晚睡的原因有很多：有时也许是因为什么事情没能按时躺上床，有时也许是躺上床了却许久没睡着。

让我们继续用小麦同学作例子吧。

对于小麦同学来说，他的思绪在晚上更容易不安分——如果晚上摄入的蛋白和碳水更多，他晚间的精力会过于充沛；睡前看屏幕稍微久一点，他会更难放松下来；假如通知群或工作群蹦出些什么消息，他的脑子会噼里啪啦地转起来，下意识地协调明天要做的事情，然后想的东西越来越多，收也收不住……同时小麦的舍友晚上会很活跃地进行着各种赛事，所以想好好地睡上一觉并不容易。

整理要点，制成一张张WOOP卡片：

- 晚餐不宜太丰盛。

```
Wish: 晚餐控制营养条件
Outcome: 按时睡觉，第二天轻松起床、精力充沛
Obstacle: 不得不与他人出去吃大餐（e.g.被同学拉去外面吃饭、亲戚儿子的百日酒）
Plan: 反复提醒自己，只吃一碗半！少夹肉多夹菜！
```

- 八点半后不进食，少饮水。

```
Wish: 不扰乱生理节律
Outcome: 按时睡觉，第二天轻松起床、精力充沛
Obstacle: 八点半后，宿友给我递来了一块巧克力
Plan: 委婉、礼貌地谢绝
```

- 最迟九点结束活动，回到宿舍。

```
Wish: 及时上床睡觉
Outcome: 按时睡觉，第二天轻松起床、精力充沛
Obstacle: 到了九点闹钟响起时，事情还没做完
Plan: 冷漠地将各种物品塞进书包
```

- 九点后尽量不看手机，特别是不能点开社交媒体如微信、知乎和知识星球（晚间才出现的消息通常留到第二天早上处理也没问题），专心做完洗漱杂活然后立即睡觉。

```
Wish: 不让杂乱信息燃起自己的精神熵
Outcome: 按时睡觉，第二天轻松起床、精力充沛
Obstacle: 
微信传来通知，或是自己想点开微信看还有什么事情；
（或是更直接的：）手指下意识移到通知栏或是某一APP的图标上方
Plan: 
手指挪开，熄灭屏幕！想想自己现在要做什么
（除了刷牙冲凉洗衣上床以外通常不应有别的事情）
```

（这一个环节还可以上一些保险：利用手机的辅助工具来控制信息噪音，以起到眼不见为净的效果。例如iOS用户系统自带的睡眠时间免打扰和屏幕时间控制能设定时间范围，分别使通知中心和APP图标暗淡下来，新消息不会显示具体内容，APP图标不会有小红点。）

![Downtime](https://upload-images.jianshu.io/upload_images/15376232-4d72f04984c35c91.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![Downtime-WeChat](https://upload-images.jianshu.io/upload_images/15376232-16b0edd826b64303.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

- 如果很不幸又清醒了过来，保持平和。将注意放在合适的地方。

```
Wish: 避免自己因没能睡着而焦虑
Outcome: 尽早睡着
Obstacle: 清醒
Plan: 腹式深呼吸（或是478呼吸），并将听觉集中在睡前音乐上
```

当然，睡眠涉及的因素太多了，这里没有全部解决，例如“被窝的温度应当适中”，等等。

由于各种原因，我为了「按时睡觉」这个愿望头疼了很久。WOOP参与进来后，我离愿望正越来越近。

以上卡片并不是一步到位生成的，是多次摸索、练习的产物。难怪厄廷根老师让我们各种情形下都做一下WOOP。

---

看完了这篇文章，你是不是更有信心掌握这个技能了？另外你如果有什么想法，欢迎吐槽、交流:D

## Reference

- [WOOP工具箱 — WOOP my life](http://woopmylife.org/woop-3)（需要梯子）：这个网站有干货哦，你如果因时间、精力有限，只想学习、练习WOOP技能而非关心其它细节，那么实际上不一定要看《WOOP思维心理学》。
- 厄廷根《WOOP思维心理学》
- 威廉厄姆《为什么学生不喜欢上学?》
- 阳志平[《行动派》](https://mp.weixin.qq.com/s/h2di9jlO8T1BAoxwqq-7ow)
- [Biohackers Handbook-  Sleep](https://biohackingbook.com/files/2015/11/Biohackers_Handbook-Sleep.pdf)
- 华为运动健康APP中的睡眠指导

感谢阳老师PUSH我输出了一把😁

## changelog

190520 结合开智同学wangyubo123和微明的建议改动一些细节。
190514 填充完成第一版。结合开智同学nowherekai的建议改动一些细节。
190512 建立文档，构思基本思路。

**Comment by MaiYunfei2000** [comment]
[WOOP工具箱 — WOOP my life](http://woopmylife.org/woop-3)（需要梯子）

**Comment by MaiYunfei2000** [comment]
## 下篇 WOOP进阶练习

（🚜施工中）

**Comment by nowherekai** [comment]
“笨方法”学WOOP 当title不好，WOOP其实并不复杂

**Comment by nowherekai** [comment]
英文截图可以换成中文的，目标用户是中文用户

**Comment by nowherekai** [comment]
苹果手机上App Store也可以直接搜索WOOP进行下载，用法和安卓一样

**Comment by nowherekai** [comment]
“可以代表WOOP的前三个字母。”以及“可以代表WOOP的后两个字母”用法不恰当，其实是反过来的，WOOP的前三个字母代表心理对比，P代笔执行意图。

**Comment by nowherekai** [comment]
“WOOP的四大食用步骤也很好记”应该是“使用步骤”

**Comment by nowherekai** [comment]
文章中的例子不是太好，用WOOP方法执行WOOP其实理解起来有一些思考成本，可以换成早起做计划或者早睡不熬夜等

**Comment by MaiYunfei2000** [comment]
> “笨方法”学WOOP 当title不好，WOOP其实并不复杂

谢提醒。我原本考虑的是学WOOP容易，内化WOOP难，但是内化它本身没什么特殊法子，就是多练WOOP，于是就想出把“学”改成“练”。但是打字的时候还是自然而然打成了“学”……

**Comment by MaiYunfei2000** [comment]
> 苹果手机上App Store也可以直接搜索WOOP进行下载，用法和安卓一样

√

**Comment by MaiYunfei2000** [comment]
这里似乎有个矛盾：WOOP本身很简单，但是我们倾向把它搞复杂，然后这个从复杂回到简单的过程就比较复杂。

目前只能认为我正经做WOOP做得很少。

**Comment by MaiYunfei2000** [comment]
> 英文截图可以换成中文的，目标用户是中文用户

Mark

**Comment by MaiYunfei2000** [comment]
> “WOOP的四大食用步骤也很好记”应该是“使用步骤”

√

**Comment by MaiYunfei2000** [comment]
> “可以代表WOOP的前三个字母。”以及“可以代表WOOP的后两个字母”用法不恰当，其实是反过来的，WOOP的前三个字母代表心理对比，P代笔执行意图。

理解了，不过保留意见。

执行意图本身就是if-then脚本。但是用在WOOP中，它的if必须为Obstacle，这一点从APP的操作可以很明显看出来。我的错误示范就是在Plan里输入了if-then脚本，结果它拿Obstacle输入的东西作为if，Plan里输入的内容作为then。也就是说，按照这个思路，在WOOP中执行意图的使用是受限的，但脱离开WOOP，啊 被别人叫走了

**Comment by MaiYunfei2000** [comment]
也许需要强调一下这个“笨方法”——跟着APP的操作写出合理的卡片。不断写不断写，练习使用WOOP。

然后没必要把文章搞成上下篇，直接砍掉下篇？（这样主题更简单一些。

**Comment by MaiYunfei2000** [comment]
还有另一种自暴自弃式的解法：直接把APP的存在推给大家。APP本来就简单到不需要使用教程，APP连官方文档都没有（WOOP倒是有）。

也许这不一定是自暴自弃，而是从决定出文章的一开始就错了？——这个东西那么简单，非要折腾得那么复杂，何必呢（？？？）

**Comment by MaiYunfei2000** [comment]
至于案例……我还是没有觉得ok的替代版。第一个错误示范中“为了做WOOP而做一次WOOP”是因为厄廷根老师在书中时不时说我们应当各种时候都WOOP一下。那么拿到WOOP这个技能之后，我们应当优先做的是不是让自己生成习惯——使用WOOP的习惯——呢？于是做了这个WOOP。这里涉及到的技巧也许就是「元」。至于“下篇”，这个确实不是很重要，最重要的还是先结合自己的生活需要练起WOOP来再说。

**Comment by wangyubo123** [comment]
WOOP另一个隐含的应该是SMART原则和简单原则，每次只一个不可再分的小目标，具化之，这样认知负荷小。

**Comment by WangYuBo** [comment]
和小伙伴做了一个WOOP小程序，欢迎小伙伴们试用，小程序里搜 “草莓WOOP”～

**Comment by MaiYunfei2000** [comment]
> WOOP另一个隐含的应该是SMART原则和简单原则，每次只一个不可再分的小目标，具化之，这样认知负荷小。

是的，这个思路可以与阳老师在《构建优雅的知识创造系统》中的思路对接起来。WOOP是最小的卡片层级，而若干的WOOP卡片可以建构成一套行动系统。

**Comment by MaiYunfei2000** [comment]
知识星球-开智校友会

微明：我觉得你的第一个愿望“早起做woop”的结果/幻想应该是“果然早起了、并真的做了一次woop、做完感觉如何如何”，否则你的愿望应该改成“按时完成明天所有规划好的事情”。

麦云飞 回复 微明：[强]我明白了，我的思路太跳了，却没解释清楚。因为觉得 为一天所有事情规划时间 有时会不太靠谱，然后就想这样做：考虑今天都有什么事情，然后为这些事情都设好WOOP脚本。那我应该把表述改为“结合WOOP规划好今天的事情”之类的。这样的最美好幻想就是今天的事情都良好完成了。

Mark @todo

**Comment by MaiYunfei2000** [comment]
王钰博和微明同学的建议已补充进文。

**Comment by MaiYunfei2000** [comment]
螺旋上升的新感悟：对于WOOP，如拙文所提，心理比对和执行意图都不可少，且两者要扣好以发挥组合技的威力。但是真要提升执行力的话，执行意图是必要成分。心理比对则是一种推进剂，为了将执行意图的if-then脚本牢牢刻印在你的记忆里而发挥作用。换句话说借助格尔维茨系的武器来提升执行力的关键是把脚本嵌入长时记忆，并且要能够自如提取，从而改造个人的行动系统。

**Comment by MaiYunfei2000** [comment]
闭合信息。再次感谢开智同侪们的反馈。

**Comment by MaiYunfei2000** [comment]
文章已在开智学堂公众号发表。

[成为行动派的路上，你还差这个 APP](https://mp.weixin.qq.com/s/qWPx_iDSDVm22ekoCn-0Tw)

不过现在才发觉这种标题太传销或者鸡汤了？？容易促使人以为这款软件确实很牛逼或者很必要。
不过无所谓了……
